/* Frågedata för HP Ordquiz
   Varje fråga har: word, options (4 st, en mening var), correct-index, difficulty
   Fördelning: grund 70, medel 55, svår 55, elit 40 — totalt 220 ord */
const questions = [

  // === GRUNDNIVÅ (70 ord) ===
  { word: "Aberration", options: ["En förbättring eller uppgradering av något", "En avvikelse från det normala eller förväntade", "En logisk och tydlig förklaring", "En återkommande upprepning av ett mönster"], correct: 1, difficulty: "grund" },
  { word: "Ambivalent", options: ["Helt säker och övertygad i sin åsikt", "Totalt likgiltig inför frågan", "Klart negativt inställd till något", "Kluven mellan två motstridiga känslor"], correct: 3, difficulty: "grund" },
  { word: "Arbiträr", options: ["Bestämd slumpmässigt utan sakliga skäl", "Rättvist och balanserat avvägd", "Noggrant uträknad enligt regler", "Något som följer av naturen"], correct: 0, difficulty: "grund" },
  { word: "Koncis", options: ["Oklart formulerad och svårtolkad", "Kortfattad men ändå fullständig", "Invecklat och omständligt uttryckt", "Uttömmande i varje detalj"], correct: 1, difficulty: "grund" },
  { word: "Obskyr", options: ["Allmänt känd och uppskattad", "Enkel och lätt att förstå", "Dunkel, svårtillgänglig eller skumt betraktad", "Snabbt övergående och ytlig"], correct: 2, difficulty: "grund" },
  { word: "Preliminär", options: ["Definitivt fastställd och slutgiltig", "Tillfällig och kan komma att ändras", "Helt felaktig och måste göras om", "Försenad och ännu inte påbörjad"], correct: 1, difficulty: "grund" },
  { word: "Subtil", options: ["Tydlig och lätt att uppmärksamma", "Svag och nästan utan verkan", "Finstämd och svår att direkt lägga märke till", "Enkel och rättfram i sin natur"], correct: 2, difficulty: "grund" },
  { word: "Vederlägga", options: ["Bekräfta med övertygande bevis", "Förklara i detalj hur något fungerar", "Motbevisa något med hållbara argument", "Förstärka en befintlig uppfattning"], correct: 2, difficulty: "grund" },
  { word: "Resignerad", options: ["Full av ilska och protest", "Uppgivet accepterande inför det oundvikliga", "Förvirrad och villrådig", "Stolt och självsäker"], correct: 1, difficulty: "grund" },
  { word: "Tvetydig", options: ["Fullständigt klar och otvetydig", "Enkel att entydigt tolka", "Osäker om sitt eget uttryck", "Möjlig att förstå på två olika sätt"], correct: 3, difficulty: "grund" },
  { word: "Fatal", options: ["Helt ofarlig och betydelselös", "Ödesdiger med allvarliga följder", "Snabb och effektiv i sin verkan", "Tillfällig och snart glömd"], correct: 1, difficulty: "grund" },
  { word: "Frugal", options: ["Slösaktig med resurser", "Sparsam och måttfull i levnadssätt", "Rikt överflödande i allt", "Generös utan begränsning"], correct: 1, difficulty: "grund" },
  { word: "Explicit", options: ["Otydligt antydd eller dold", "Uttalad rakt på sak och tydligt uttryckt", "Hemlig och inte för allmänheten", "Svår att förstå utan förkunskaper"], correct: 1, difficulty: "grund" },
  { word: "Indikativ", options: ["Otydlig och ingenting pekande", "Helt avgörande och slutgiltig", "Som pekar mot eller antyder något", "Slumpmässig och utan riktning"], correct: 2, difficulty: "grund" },
  { word: "Legitim", options: ["Laglig och allmänt erkänd", "Falsk och bedräglig", "Dold för allmänheten", "Tillfällig och utan tyngd"], correct: 0, difficulty: "grund" },
  { word: "Restriktiv", options: ["Helt fri från begränsningar", "Begränsande och återhållsam", "Mild och efterlåten", "Snabbt föränderlig"], correct: 1, difficulty: "grund" },
  { word: "Hypotetisk", options: ["Verklig och påvisbar", "Tänkt som ett antagande", "Slumpmässig och oförutsägbar", "Färdig och slutbehandlad"], correct: 1, difficulty: "grund" },
  { word: "Notorisk", options: ["Helt okänd för gemene man", "Välkänd för något negativt", "Nyligen upptäckt", "Av tillfällig karaktär"], correct: 1, difficulty: "grund" },
  { word: "Paradoxal", options: ["Helt logisk och självklar", "Motsägelsefull men ändå sann", "Enkel att förklara kort", "Självklar för alla"], correct: 1, difficulty: "grund" },
  { word: "Destruktiv", options: ["Uppbyggande och stärkande", "Skadlig och nedbrytande till sin verkan", "Snabb och effektiv", "Mild och återhållsam"], correct: 1, difficulty: "grund" },
  { word: "Klandervärd", options: ["Värd allmänt beröm", "Förtjänar berömvärt erkännande", "Förtjänar kritik och ogillande", "Helt neutral och opåtaglig"], correct: 2, difficulty: "grund" },
  { word: "Försumlig", options: ["Mycket noggrann och ansvarsfull", "Slarvig och nonchalant inför sina plikter", "Snabb och effektiv", "Aktiv och engagerad"], correct: 1, difficulty: "grund" },
  { word: "Underminera", options: ["Förstärka något stegvis", "Försvaga något inifrån utan att synas", "Bygga upp från grunden", "Skydda mot angrepp"], correct: 1, difficulty: "grund" },
  { word: "Hävdvunnen", options: ["Nyligen införd och obeprövad", "Av tillfällig karaktär", "Sedan länge etablerad genom tradition", "Slumpmässigt vald"], correct: 2, difficulty: "grund" },
  { word: "Oförvitlig", options: ["Skyldig till flera förseelser", "Felfri och oantastlig i sitt handlande", "Otydlig i sina avsikter", "Ovanlig och udda"], correct: 1, difficulty: "grund" },
  { word: "Tillstymmelse", options: ["Det slutgiltiga avslutet", "En allra första antydan eller början", "Ett olösligt problem", "Ett slutgiltigt resultat"], correct: 1, difficulty: "grund" },
  { word: "Uppfordrande", options: ["Vänlig och efterlåten", "Manande och kravställande", "Otydlig i sitt tilltal", "Passiv och avvaktande"], correct: 1, difficulty: "grund" },
  { word: "Förespegla", options: ["Avslöja sanningen direkt", "Tydligt visa hur något är", "Måla upp en falsk förväntan för någon", "Förklara grundligt i detalj"], correct: 2, difficulty: "grund" },
  { word: "Konsekvent", options: ["Ologisk och motstridig", "Följdriktig och utan avsteg från sin linje", "Slumpmässig och tillfällig", "Snabbt skiftande"], correct: 1, difficulty: "grund" },
  { word: "Temporär", options: ["Bestående och oföränderlig", "Tillfällig och övergående", "Snabb och plötslig", "Krävande att genomföra"], correct: 1, difficulty: "grund" },
  { word: "Divergerande", options: ["Som löper samman mot en punkt", "Som drar isär åt olika håll", "Helt identiska med varandra", "Snabbt övergående"], correct: 1, difficulty: "grund" },
  { word: "Fundamental", options: ["Ytlig och utan djup", "Grundläggande och helt avgörande", "Tillfällig och flyktig", "Svår att åstadkomma"], correct: 1, difficulty: "grund" },
  { word: "Marginell", options: ["Helt central och avgörande", "Obetydligt liten i omfattning", "Mycket tydlig och synlig", "Stor och övergripande"], correct: 1, difficulty: "grund" },
  { word: "Kompromiss", options: ["En oförsonlig konflikt", "En uppgörelse där båda ger efter något", "Ett olösligt problem", "En färdig slutlösning"], correct: 1, difficulty: "grund" },
  { word: "Analog", options: ["Jämförbar eller liknande något annat", "Helt olik och utan likheter", "Slumpmässig och oförutsägbar", "Snabbt övergående"], correct: 0, difficulty: "grund" },
  { word: "Distanserad", options: ["Nära engagerad och närvarande", "Tar avstånd och håller sig på håll", "Snabbt framfusig", "Hjärtlig och varm"], correct: 1, difficulty: "grund" },
  { word: "Progressiv", options: ["Bakåtsträvande och traditionell", "Framåtriktad och förändringsvänlig", "Helt stillastående", "Slumpmässigt växlande"], correct: 1, difficulty: "grund" },
  { word: "Evident", options: ["Svårbegripligt och dolt", "Tydligt och uppenbart för alla", "Hemligt och fördolt", "Tungt att förklara"], correct: 1, difficulty: "grund" },
  { word: "Relativ", options: ["Absolut och oberoende", "Beroende av sitt sammanhang", "Snabbt föränderlig", "Enkel och självklar"], correct: 1, difficulty: "grund" },
  { word: "Generös", options: ["Snål och njugg med sitt", "Frikostig och villig att ge", "Otydlig i sina avsikter", "Svår att få kontakt med"], correct: 1, difficulty: "grund" },
  { word: "Kritisk", options: ["Okritiskt accepterande", "Granskande och ifrågasättande", "Brådskande och stressad", "Helt neutral och opartisk"], correct: 1, difficulty: "grund" },
  { word: "Abstrakt", options: ["Konkret och gripbar", "Teoretisk och icke-sinnlig", "Enkel och lätt att förstå", "Snabbt övergående"], correct: 1, difficulty: "grund" },
  { word: "Konventionell", options: ["Udda och avvikande", "Traditionell och enligt rådande norm", "Slumpmässigt vald", "Nyskapande och oprövad"], correct: 1, difficulty: "grund" },
  { word: "Ambitiös", options: ["Lat och utan drivkraft", "Målmedveten och strävande efter mycket", "Hastig och oövertänkt", "Otydlig i sina mål"], correct: 1, difficulty: "grund" },
  { word: "Exkludera", options: ["Inkludera och räkna in", "Utesluta eller lämna utanför", "Förklara i detalj", "Förstärka ett budskap"], correct: 1, difficulty: "grund" },
  { word: "Eliminera", options: ["Skapa något nytt", "Avlägsna eller ta bort helt", "Förklara noggrant", "Öka i omfattning"], correct: 1, difficulty: "grund" },
  { word: "Dominera", options: ["Underordna sig andras vilja", "Ha en styrande och överordnad ställning", "Försvaga sig själv", "Krympa i betydelse"], correct: 1, difficulty: "grund" },
  { word: "Konsekvens", options: ["Den ursprungliga orsaken", "En följd eller ett resultat av något", "Ett problem som uppstår", "Ett slumpmässigt inslag"], correct: 1, difficulty: "grund" },
  { word: "Neutral", options: ["Starkt partisk åt ena hållet", "Opartisk och utan att ta ställning", "Aktivt inblandad", "Snabbt växlande i åsikt"], correct: 1, difficulty: "grund" },
  { word: "Ignorera", options: ["Uppmärksamma noggrant", "Strunta i eller låtsas inte se", "Förstå till fullo", "Förklara i detalj"], correct: 1, difficulty: "grund" },
  { word: "Kontradiktion", options: ["En fullständig likhet", "En logisk motsägelse", "Ett praktiskt problem", "En tydlig förklaring"], correct: 1, difficulty: "grund" },
  { word: "Preciserad", options: ["Otydligt och vagt formulerad", "Noggrant och specifikt angiven", "Hastigt sammanslängd", "Endast tillfälligt giltig"], correct: 1, difficulty: "grund" },
  { word: "Reducera", options: ["Öka i storlek eller antal", "Minska eller dra ner på något", "Förklara grundligt", "Skapa från grunden"], correct: 1, difficulty: "grund" },
  { word: "Exponera", options: ["Dölja från insyn", "Visa upp eller utsätta för något", "Förklara sammanhanget", "Skydda från påverkan"], correct: 1, difficulty: "grund" },
  { word: "Komplex", options: ["Enkel och okonstlad", "Invecklad och bestående av många delar", "Hastig och snabb", "Helt genomskinlig"], correct: 1, difficulty: "grund" },
  { word: "Stabil", options: ["Svajig och oberäknelig", "Stadig och utan plötsliga förändringar", "Ilande snabb", "Komplicerat uppbyggd"], correct: 1, difficulty: "grund" },
  { word: "Flexibel", options: ["Stel och omöjlig att böja", "Anpassningsbar efter omständigheter", "Snabb i sina beslut", "Otydlig i sitt uttryck"], correct: 1, difficulty: "grund" },
  { word: "Permanent", options: ["Endast för stunden", "Varaktig och bestående över tid", "Hastigt påkommande", "Otydlig i sin räckvidd"], correct: 1, difficulty: "grund" },
  { word: "Approximation", options: ["Ett helt exakt värde", "En ungefärlig uppskattning", "Ett olösligt problem", "En slutgiltig lösning"], correct: 1, difficulty: "grund" },
  { word: "Kapitulera", options: ["Stå på sig till det sista", "Ge upp och erkänna sig besegrad", "Ifrågasätta villkoren", "Förhandla fram bättre avtal"], correct: 1, difficulty: "grund" },
  { word: "Motvillig", options: ["Helhjärtat ivrig och villig", "Ovillig men ändå medgörlig", "Helt vägrande att delta", "Glättigt entusiastisk"], correct: 1, difficulty: "grund" },
  { word: "Signifikant", options: ["Obetydlig och försumbar", "Betydelsefull och av vikt", "Slumpmässig och oberäknelig", "Oklar till sin innebörd"], correct: 1, difficulty: "grund" },
  { word: "Rigorös", options: ["Slapp och efterlåten", "Mycket sträng och noggrann", "Flexibel och anpassningsbar", "Snabb och ytlig"], correct: 1, difficulty: "grund" },
  { word: "Prioritera", options: ["Behandla alla ärenden lika", "Sätta något främst före annat", "Skjuta upp till senare", "Helt avstå från val"], correct: 1, difficulty: "grund" },
  { word: "Kulminera", options: ["Påbörjas svagt och trevande", "Nå sin allra högsta punkt", "Avta långsamt till noll", "Stå stilla utan förändring"], correct: 1, difficulty: "grund" },
  { word: "Trivial", options: ["Djup och mångbottnad", "Obetydlig och vardaglig", "Mycket allvarlig och tung", "Helt oersättlig i sitt slag"], correct: 1, difficulty: "grund" },
  { word: "Ikonisk", options: ["Helt okänd i sammanhanget", "Symbolisk och omedelbart igenkännlig", "Nyligen introducerad", "Otydligt profilerad"], correct: 1, difficulty: "grund" },
  { word: "Autentisk", options: ["Förfalskad och icke-äkta", "Äkta och oförvanskad", "Kopierad från annat håll", "Otydlig till sitt ursprung"], correct: 1, difficulty: "grund" },
  { word: "Disträ", options: ["Fullt fokuserad på uppgiften", "Tankspridd och frånvarande i stunden", "Mycket noggrann i detaljerna", "Stressad och forcerad"], correct: 1, difficulty: "grund" },
  { word: "Omdiskuterad", options: ["Allmänt erkänd utan invändningar", "Föremål för skilda åsikter och debatt", "Helt okänd för allmänheten", "Av tillfällig betydelse"], correct: 1, difficulty: "grund" },

  // === MEDELNIVÅ (55 ord) ===
  { word: "Lakonisk", options: ["Utförligt och omständligt formulerad", "Kort och kärnfull i sitt uttryck", "Otydlig och svårbegriplig", "Ironisk och något hånfull"], correct: 1, difficulty: "medel" },
  { word: "Repressiv", options: ["Frigörande och uppmuntrande", "Förtryckande och begränsande för friheten", "Tillfällig till sin natur", "Opartisk och balanserad"], correct: 1, difficulty: "medel" },
  { word: "Sporadisk", options: ["Regelbundet återkommande", "Oregelbunden och glest förekommande", "Ständigt pågående", "Avgörande och stark"], correct: 1, difficulty: "medel" },
  { word: "Pragmatisk", options: ["Strikt teoretisk och abstrakt", "Praktiskt inriktad på vad som fungerar", "Emotionellt styrd", "Traditionsbunden i sin syn"], correct: 1, difficulty: "medel" },
  { word: "Dogmatisk", options: ["Öppen för alla synsätt", "Låst fast vid givna läror utan omprövning", "Tvivelaktig i sina grunder", "Vetenskapligt prövande"], correct: 1, difficulty: "medel" },
  { word: "Eklektisk", options: ["Strikt hållen till en enda tradition", "Sammansatt av delar från många olika håll", "Helt originell och utan förebilder", "Motsägelsefull och osammanhängande"], correct: 1, difficulty: "medel" },
  { word: "Empirisk", options: ["Baserad enbart på teoretiska antaganden", "Byggd på erfarenhet och observation", "Ren spekulation utan grund", "Dikterad av tradition"], correct: 1, difficulty: "medel" },
  { word: "Nominell", options: ["Helt verklig och reell", "Enbart till namnet men inte i praktiken", "Överlägsen i värde", "Omsorgsfullt uträknad"], correct: 1, difficulty: "medel" },
  { word: "Altruistisk", options: ["Själviskt inriktad på egen vinst", "Osjälvisk och inriktad på andras väl", "Likgiltig inför andras behov", "Kalkylerande och beräknande"], correct: 1, difficulty: "medel" },
  { word: "Stringent", options: ["Lös och flyttbar i sina ramar", "Strikt logisk och följdriktig", "Känslomässigt präglad", "Fri och öppen i formen"], correct: 1, difficulty: "medel" },
  { word: "Ortodox", options: ["Avvikande från rådande tradition", "Strikt trogen mot etablerad lära", "Tveksam till vedertagna regler", "Modern och nyskapande"], correct: 1, difficulty: "medel" },
  { word: "Symbios", options: ["En ensidig relation med förlorare", "Samverkan där båda parter har nytta av varandra", "En rak konfliktsituation", "Ett tillfälligt möte"], correct: 1, difficulty: "medel" },
  { word: "Reciprok", options: ["Ensidig och icke-besvarad", "Ömsesidig och gående åt båda hållen", "Slumpvist växlande", "Helt likgiltig"], correct: 1, difficulty: "medel" },
  { word: "Oförbehållsam", options: ["Full av reservationer och invändningar", "Fullständig och utan förbehåll", "Tvekande och osäker", "Hemlighetsfull"], correct: 1, difficulty: "medel" },
  { word: "Unison", options: ["I splittring med skilda röster", "I samklang och med en stämma", "I rak konflikt med varandra", "Av tillfällig art"], correct: 1, difficulty: "medel" },
  { word: "Kongenial", options: ["Helt oförenlig till sin natur", "Själsligt besläktad och stämmer överens", "Endast ytligt lik", "Avsiktligt efterliknad"], correct: 1, difficulty: "medel" },
  { word: "Exemplarisk", options: ["Medelmåttig och intetsägande", "Föredömlig och värd att ta efter", "Ovanligt misslyckad", "Helt ordinär"], correct: 1, difficulty: "medel" },
  { word: "Prekär", options: ["Mycket stabil och säker", "Ytterst osäker och känslig", "Tydligt löst problem", "Ovidkommande för saken"], correct: 1, difficulty: "medel" },
  { word: "Reminiscens", options: ["En helt ny upplevelse", "En hågkomst eller spår från förr", "En framtida förutsägelse", "Ett noggrant bevis"], correct: 1, difficulty: "medel" },
  { word: "Schablon", options: ["En unik och personlig lösning", "En förenklad mall eller stereotyp", "Ett nyskapat konstverk", "En komplex detaljerad plan"], correct: 1, difficulty: "medel" },
  { word: "Manifestera", options: ["Dölja eller hålla hemligt", "Tydligt uppenbara eller visa fram", "Ifrågasätta med kritik", "Upplösa i sina delar"], correct: 1, difficulty: "medel" },
  { word: "Polarisera", options: ["Förena alla kring en gemensam linje", "Dela upp i starkt motsatta läger", "Mjuka upp en stel struktur", "Hålla helt oberört"], correct: 1, difficulty: "medel" },
  { word: "Koherens", options: ["Brist på inre sammanhang", "Logiskt sammanhang mellan delarna", "Slumpmässig ordning", "Fullständig motsägelse"], correct: 1, difficulty: "medel" },
  { word: "Implicit", options: ["Rakt och tydligt utsagd", "Underförstådd utan att sägas rent ut", "Helt saknad i sammanhanget", "Anspelande på felaktig källa"], correct: 1, difficulty: "medel" },
  { word: "Cynisk", options: ["Naivt troende på andras godhet", "Misstänksam mot andras motiv och idealism", "Överdrivet entusiastisk", "Osäker och tveksam"], correct: 1, difficulty: "medel" },
  { word: "Eufori", options: ["Mild och dov känsla", "Överväldigande känsla av lycka", "Djup sorg och modlöshet", "Allmän likgiltighet"], correct: 1, difficulty: "medel" },
  { word: "Melankoli", options: ["Uppsluppen glädje", "Stillsam och tung sorg eller svårmod", "Rasande ilska", "Fullständig lugn neutralitet"], correct: 1, difficulty: "medel" },
  { word: "Apati", options: ["Intensivt engagemang", "Avtrubbad liknöjdhet och handlingsförlamning", "Plötslig ilska", "Skarp uppmärksamhet"], correct: 1, difficulty: "medel" },
  { word: "Pedantisk", options: ["Lättsinnig och ytlig", "Överdrivet petig och noggrann med små detaljer", "Kreativ och fri", "Grovt slarvig"], correct: 1, difficulty: "medel" },
  { word: "Tendentiös", options: ["Neutral och balanserad i framställningen", "Partisk och vinklad i en viss riktning", "Helt utan budskap", "Strängt vetenskaplig"], correct: 1, difficulty: "medel" },
  { word: "Inkorporera", options: ["Utesluta och avskilja", "Införliva och göra till en del av helheten", "Förbjuda från deltagande", "Separera i beståndsdelar"], correct: 1, difficulty: "medel" },
  { word: "Appellera", options: ["Avvisa utan diskussion", "Vädja eller rikta en uppmaning till någon", "Tyst lyssna utan respons", "Mekaniskt upprepa"], correct: 1, difficulty: "medel" },
  { word: "Antydan", options: ["Ett helt tydligt utsagd påstående", "En försiktig hänvisning utan att säga rent ut", "En öppen konfrontation", "En noggrann beskrivning"], correct: 1, difficulty: "medel" },
  { word: "Skepsis", options: ["Okritisk tilltro till allt", "Tvivel och kritiskt ifrågasättande", "Blindvärdigt accepterande", "Likgiltighet inför sanningen"], correct: 1, difficulty: "medel" },
  { word: "Diametral", options: ["Nära liknande i alla avseenden", "Rakt motsatt och oförenlig", "Delvis överlappande", "Otydligt skild"], correct: 1, difficulty: "medel" },
  { word: "Vokal", options: ["Tyst och hållen inom sig", "Ljudligt och öppet uttryckt", "Skriftlig och formell", "Underförstådd och dold"], correct: 1, difficulty: "medel" },
  { word: "Latent", options: ["Tydligt framträdande och aktiv", "Dold men närvarande under ytan", "Helt upplöst och borta", "Starkt överdriven"], correct: 1, difficulty: "medel" },
  { word: "Profan", options: ["Helig eller religiöst laddad", "Världslig och icke-religiös till sin natur", "Hemlig och mystisk", "Rituellt präglad"], correct: 1, difficulty: "medel" },
  { word: "Eminent", options: ["Medelmåttig och oframstående", "Framstående och av stor betydelse", "Tillfälligt uppmärksammad", "Helt anonym i sitt fält"], correct: 1, difficulty: "medel" },
  { word: "Eterisk", options: ["Tung och jordnära", "Lätt, svävande och nästan andlig", "Grov och rå till formen", "Pregnant och färglös"], correct: 1, difficulty: "medel" },
  { word: "Dekadent", options: ["I stark tillväxt och blomstring", "I förfall efter en tidigare storhetsperiod", "Stabilt oförändrad", "Nyligen uppkommen"], correct: 1, difficulty: "medel" },
  { word: "Obönhörlig", options: ["Möjlig att vika sig för böner", "Skoningslös och omöjlig att beveka", "Mild och förstående", "Tveksam och osäker"], correct: 1, difficulty: "medel" },
  { word: "Kallsinnig", options: ["Varmt engagerad och medkännande", "Känslokall och oberörd av det som sker", "Eldigt passionerad", "Osäker och famlande"], correct: 1, difficulty: "medel" },
  { word: "Oblyg", options: ["Försynt och tillbakadragen", "Fräck och utan respektfull återhållsamhet", "Mjuk och varsam", "Rädd och försiktig"], correct: 1, difficulty: "medel" },
  { word: "Tarvlig", options: ["Utstuderat elegant", "Simpel, smaklös och bristande i kvalitet", "Storslaget praktfull", "Osedvanligt utsökt"], correct: 1, difficulty: "medel" },
  { word: "Förhärligande", options: ["Nedsättande och kritiskt belyst", "Lovprisande och upphöjande till skyarna", "Nyktert beskrivande", "Noggrant kritiserande"], correct: 1, difficulty: "medel" },
  { word: "Fragmentarisk", options: ["Helgjuten och sammanhållen", "Splittrad och uppdelad i ofullständiga delar", "Grundlig och uttömmande", "Helt enhetlig"], correct: 1, difficulty: "medel" },
  { word: "Homogen", options: ["Enhetlig och av samma slag genom hela", "Blandad av många olika delar", "Motstridig i sin uppbyggnad", "Obestämd till sin natur"], correct: 0, difficulty: "medel" },
  { word: "Heterogen", options: ["Enhetlig och likartad", "Blandad och sammansatt av olikartade delar", "Tom på innehåll", "Hårt sammanhållen"], correct: 1, difficulty: "medel" },
  { word: "Reservation", options: ["Entusiastisk uppslutning utan tvekan", "Ett förbehåll eller en invändning", "En definitiv bekräftelse", "En neutral observation"], correct: 1, difficulty: "medel" },
  { word: "Hedonistisk", options: ["Strävande efter lidande och försakelse", "Inriktad på njutning och lustupplevelser", "Fullständigt likgiltig", "Målinriktad på plikt"], correct: 1, difficulty: "medel" },
  { word: "Oroväckande", options: ["Lugnande och betryggande", "Som ger anledning till oro och bekymmer", "Helt neutralt och ointressant", "Tydligt uppmuntrande"], correct: 1, difficulty: "medel" },
  { word: "Översiktlig", options: ["Detaljerad in i minsta smådel", "Tydligt sammanfattande i sina huvuddrag", "Otydlig och rörig", "Mycket specifik och smal"], correct: 1, difficulty: "medel" },
  { word: "Oavsiktlig", options: ["Noggrant planerad i förväg", "Gjord utan avsikt eller medvetet val", "Med tydligt uttalat syfte", "Upprepat övad"], correct: 1, difficulty: "medel" },
  { word: "Ymnig", options: ["Knappt förekommande", "Rikligt och överflödigt förekommande", "Jämnt utspridd", "Mycket sällsynt"], correct: 1, difficulty: "medel" },

  // === SVÅR NIVÅ (55 ord) ===
  { word: "Asketisk", options: ["Livsnjutande och bekvämlighetsinriktad", "Strängt avhållsam från njutningar och bekvämlighet", "Ytligt fåfäng", "Ohämmat utsvävande"], correct: 1, difficulty: "svar" },
  { word: "Stipulera", options: ["Underförstått antyda villkor", "Uttryckligen föreskriva eller fastställa villkor", "Upphäva gällande regler", "Ignorera förutsättningar"], correct: 1, difficulty: "svar" },
  { word: "Emfatisk", options: ["Svagt och försiktigt framfört", "Uttryckt med starkt eftertryck och kraft", "Nästan omärkligt antytt", "Helt utan betoning"], correct: 1, difficulty: "svar" },
  { word: "Vigilant", options: ["Slö och ouppmärksam", "Vaksam och alltid på sin vakt", "Distraherad och frånvarande", "Godtrogen och oförsiktig"], correct: 1, difficulty: "svar" },
  { word: "Bombastisk", options: ["Enkelt och sakligt hållen", "Överdrivet högtravande och pompös", "Kortfattat och neutralt", "Tyst och diskret"], correct: 1, difficulty: "svar" },
  { word: "Obskurantism", options: ["Iver att sprida kunskap brett", "Motstånd mot upplysning och kritiskt tänkande", "Stark tro på vetenskap", "Klarhet och öppenhet"], correct: 1, difficulty: "svar" },
  { word: "Konfabulera", options: ["Korrekt återge minnen", "Hitta på minnen som känns äkta", "Helt glömma bort händelser", "Förneka kända fakta"], correct: 1, difficulty: "svar" },
  { word: "Obfuskera", options: ["Tydligt klargöra för alla", "Avsiktligt göra något otydligt eller svårbegripligt", "Summera kort och koncist", "Förenkla ett komplext ämne"], correct: 1, difficulty: "svar" },
  { word: "Hypostasera", options: ["Upplösa ett konkret ting", "Behandla något abstrakt som vore det konkret", "Bevisa empiriskt", "Endast teoretiskt resonera"], correct: 1, difficulty: "svar" },
  { word: "Paradigmatisk", options: ["Helt avvikande från regeln", "Mönstergill och normbildande inom sitt fält", "Av marginell betydelse", "Snabbt föråldrad"], correct: 1, difficulty: "svar" },
  { word: "Apokryfisk", options: ["Väldokumenterad och officiellt erkänd", "Av tvivelaktigt ursprung eller oäkta", "Allmänt accepterad sanning", "Helt ny och obeprövad"], correct: 1, difficulty: "svar" },
  { word: "Sofistikerad", options: ["Enkel och okonstlad", "Förfinad, kultiverad och mångbottnad", "Rå och outvecklad", "Primitiv i sitt utförande"], correct: 1, difficulty: "svar" },
  { word: "Emanera", options: ["Ta in och absorbera", "Strömma ut eller utgå från en källa", "Stå stilla utan rörelse", "Upplösas fullständigt"], correct: 1, difficulty: "svar" },
  { word: "Aversion", options: ["Stark attraktion till något", "Stark motvilja eller avsmak för något", "Likgiltighet inför en sak", "Försiktig nyfikenhet"], correct: 1, difficulty: "svar" },
  { word: "Introspektion", options: ["Granskning av omvärlden", "Inre granskning av egna tankar och känslor", "Ytlig iakttagelse", "Formell utredning"], correct: 1, difficulty: "svar" },
  { word: "Estetisk", options: ["Som rör det etiskt rätta", "Som rör det sköna och den sinnliga upplevelsen", "Som rör praktiskt bruk", "Som rör logiskt tänkande"], correct: 1, difficulty: "svar" },
  { word: "Insinuera", options: ["Öppet anklaga på en gång", "Antyda nedsättande utan att säga rakt ut", "Beskriva sakligt och neutralt", "Smickra överdrivet"], correct: 1, difficulty: "svar" },
  { word: "Diaspora", options: ["En enhetlig samlad folkgrupp", "En folkgrupp spridd ut över olika länder", "En nyligen bildad stat", "En tillfällig samling"], correct: 1, difficulty: "svar" },
  { word: "Nyansera", options: ["Förenkla till en enda sida", "Ge fler bottnar och skiftningar åt något", "Förvränga till motsatsen", "Bekräfta utan omprövning"], correct: 1, difficulty: "svar" },
  { word: "Obstinat", options: ["Lättledd och medgörlig", "Envist motspänstig och oböjlig", "Mycket anpassningsbar", "Tvekande i sitt beslut"], correct: 1, difficulty: "svar" },
  { word: "Kontemplativ", options: ["Rastlöst handlingsinriktad", "Eftertänksam och fördjupad i stilla tanke", "Ytligt reagerande", "Aggressivt debatterande"], correct: 1, difficulty: "svar" },
  { word: "Solitär", options: ["Omgiven av sällskap alltid", "Ensam och avskild från andra", "Del av en stor grupp", "Tillfälligt avstängd"], correct: 1, difficulty: "svar" },
  { word: "Ekvivalent", options: ["Helt olik i värde", "Likvärdig eller motsvarande något annat", "Överlägsen i varje avseende", "Tvetydig till sin natur"], correct: 1, difficulty: "svar" },
  { word: "Dispyt", options: ["Tyst samförstånd i frågan", "En hetsig ordväxling eller tvist", "Tydlig överenskommelse", "Neutral observation"], correct: 1, difficulty: "svar" },
  { word: "Affektation", options: ["Äkta och naturligt beteende", "Tillgjord eller konstlad uppträdande", "Uppriktig känsla", "Helt neutralt uttryck"], correct: 1, difficulty: "svar" },
  { word: "Rudimentär", options: ["Fullt utvecklad och förfinad", "Mycket grundläggande och outvecklad", "Överdrivet komplicerad", "Förfallen och sönderfallande"], correct: 1, difficulty: "svar" },
  { word: "Substantiell", options: ["Tunn och obetydlig", "Av verklig tyngd och betydelse", "Rent kosmetisk", "Av oklar beskaffenhet"], correct: 1, difficulty: "svar" },
  { word: "Dilettantisk", options: ["Mästerligt utförd", "Amatörmässig och utan djup kunnande", "Professionellt exakt", "Rutinerad och säker"], correct: 1, difficulty: "svar" },
  { word: "Opportun", options: ["Olägligt och illa valt", "Läglig och passande för stunden", "För sent i tiden", "Ovidkommande för situationen"], correct: 1, difficulty: "svar" },
  { word: "Kapricios", options: ["Stadig och förutsägbar", "Nyckfull och oberäknelig i sina infall", "Lugn och balanserad", "Strikt logisk"], correct: 1, difficulty: "svar" },
  { word: "Diffus", options: ["Skarpt konturerad", "Otydlig, spridd och svårdefinierad", "Fokuserad på en punkt", "Tydligt ämnesbunden"], correct: 1, difficulty: "svar" },
  { word: "Impassibel", options: ["Starkt känslomässigt påverkad", "Oberörd och utan yttre tecken på känsla", "Snabbt upprörd", "Öppet sårbar"], correct: 1, difficulty: "svar" },
  { word: "Inkommensurabel", options: ["Lätt att jämföra", "Omöjlig att jämföra med gemensam måttstock", "Exakt mätbar", "Av likvärdigt värde"], correct: 1, difficulty: "svar" },
  { word: "Insubordination", options: ["Strikt lydnad", "Olydnad gentemot överordnad", "Självförsvar mot oförrätt", "Förhandling om villkor"], correct: 1, difficulty: "svar" },
  { word: "Preludium", options: ["Den slutliga upplösningen", "Ett inledande förspel eller första del", "En mittdel i stycket", "En avslutande kommentar"], correct: 1, difficulty: "svar" },
  { word: "Prosaisk", options: ["Upphöjd och poetisk", "Vardaglig, enkel och utan poetisk lyftning", "Utstuderat konstnärlig", "Högstämt känslosam"], correct: 1, difficulty: "svar" },
  { word: "Nimbus", options: ["Dammig och matt framtoning", "En aura eller strålglans kring någon eller något", "Ett tydligt avgränsat föremål", "En mindre detalj"], correct: 1, difficulty: "svar" },
  { word: "Ostentativ", options: ["Hemlig och undanskymd", "Iögonfallande uppvisad för att märkas", "Enkel och anspråkslös", "Omedveten och spontan"], correct: 1, difficulty: "svar" },
  { word: "Peripeti", options: ["En rak linje utan förändring", "En vändpunkt där förloppet svänger om", "Ett statiskt tillstånd", "En gradvis nedtrappning"], correct: 1, difficulty: "svar" },
  { word: "Elaborera", options: ["Summera kort och kärnfullt", "Utveckla i detalj och förfina vidare", "Kasta bort utan omsorg", "Plötsligt avsluta abrupt"], correct: 1, difficulty: "svar" },
  { word: "Komplementär", options: ["Överlappande och likartad", "Kompletterande så att helheten bildas", "Konkurrerande och oförenlig", "Överflödig och onödig"], correct: 1, difficulty: "svar" },
  { word: "Inneboende", options: ["Tillfälligt påklistrat utifrån", "Naturligt tillhörande själva saken", "Helt oförenligt med saken", "Tillfälligt lånat"], correct: 1, difficulty: "svar" },
  { word: "Vexerande", options: ["Självklart och lättlöst", "Förbryllande och svårlöst för tanken", "Helt betydelselöst", "Bekant och ordinärt"], correct: 1, difficulty: "svar" },
  { word: "Insisterande", options: ["Vikande och eftergivande", "Envist kvarhållande vid sitt anspråk", "Slumpmässigt påkommande", "Tyst och tillbakadragen"], correct: 1, difficulty: "svar" },
  { word: "Retorisk", options: ["Som rör tystnaden mellan orden", "Som rör talekonstens grepp och övertygande språk", "Som rör det rent matematiska", "Som rör enbart fakta"], correct: 1, difficulty: "svar" },
  { word: "Skrupulös", options: ["Slarvigt oansvarig", "Mycket samvetsgrann och noggrann med rätt och fel", "Helt likgiltig inför moral", "Flyktig i sin uppmärksamhet"], correct: 1, difficulty: "svar" },
  { word: "Omen", options: ["Ett resultat av något", "Ett tecken som varslar om framtiden", "En ordinär händelse", "Ett ordrikt bevis"], correct: 1, difficulty: "svar" },
  { word: "Plausibel", options: ["Helt osannolik och orimlig", "Sannolik och trovärdig utan att vara bevisad", "Matematiskt bevisad", "Otolkbart komplicerad"], correct: 1, difficulty: "svar" },
  { word: "Anomali", options: ["Bekräftelse på regeln", "En oregelbunden avvikelse från det förväntade", "En självklar följd", "En ytlig likhet"], correct: 1, difficulty: "svar" },
  { word: "Prolog", options: ["Efterord eller avslutning", "Inledande del som öppnar ett verk", "Kritisk sammanfattning", "En parentes mitt i texten"], correct: 1, difficulty: "svar" },
  { word: "Konfession", options: ["En tyst förnekelse", "En öppen bekännelse av övertygelse eller skuld", "En formell motsägelse", "En tillfällig reservation"], correct: 1, difficulty: "svar" },
  { word: "Panegyrik", options: ["Ett bitande kritiskt tal", "Ett översvallande lovtal till någons ära", "En nykter beskrivning", "En formell begravningsakt"], correct: 1, difficulty: "svar" },
  { word: "Dualism", options: ["Enhet i ett enda princip", "Uppdelning i två skilda och motverkande principer", "Mångfald i otaliga delar", "Fullständigt kaos"], correct: 1, difficulty: "svar" },
  { word: "Akribi", options: ["Slarv och godtycke", "Ytterlig exakthet och omsorgsfull noggrannhet", "Kreativ frihet utan regler", "Snabbhet framför precision"], correct: 1, difficulty: "svar" },
  { word: "Insensitiv", options: ["Fint lyhörd och uppmärksam", "Okänslig eller oförmögen att uppfatta nyanser", "Överdrivet empatisk", "Mycket noggrant reagerande"], correct: 1, difficulty: "svar" },

  // === ELITNIVÅ (40 ord) ===
  { word: "Heuristik", options: ["En strikt matematisk bevismetod", "En upptäcktsmetod som bygger på erfarenhet och tumregler", "En helt slumpmässig gissning", "En uttömmande bevisprocedur"], correct: 1, difficulty: "elit" },
  { word: "Ontologisk", options: ["Som rör språkets grammatik", "Som rör varandets och tillvarons grundläggande natur", "Som rör enbart kemiska reaktioner", "Som rör ytlig estetik"], correct: 1, difficulty: "elit" },
  { word: "Epistemologi", options: ["Läran om moraliskt rätt handlande", "Läran om kunskapens grund och gränser", "Läran om biologiska arter", "Läran om konstformer"], correct: 1, difficulty: "elit" },
  { word: "Teleologisk", options: ["Inriktad på slumpmässiga utfall", "Målinriktad där ändamålet styr förloppet", "Bakåtsträvande i sin ambition", "Helt orsaksblind"], correct: 1, difficulty: "elit" },
  { word: "Hermeneutik", options: ["Läran om mekaniska system", "Läran om tolkning av texter och meningar", "Läran om rena känslor", "Läran om militär strategi"], correct: 1, difficulty: "elit" },
  { word: "Sofism", options: ["Ett djupt och sant resonemang", "Ett skenbart riktigt men egentligen vilseledande resonemang", "En matematiskt oklanderlig slutledning", "En enkel faktabeskrivning"], correct: 1, difficulty: "elit" },
  { word: "Sui generis", options: ["Helt vanligt förekommande", "Av sitt eget unika slag utan motsvarighet", "En exakt kopia av något annat", "Typisk för sin kategori"], correct: 1, difficulty: "elit" },
  { word: "Panacea", options: ["Ett gift med dödlig verkan", "Ett universalmedel sagt bota allt", "En mild lokal salva", "En sedvanlig försiktighetsåtgärd"], correct: 1, difficulty: "elit" },
  { word: "Saturnisk", options: ["Uppsluppet lättsam", "Dyster, tungsint och grubblande till lynnet", "Ytligt glättig", "Aggressivt utåtriktad"], correct: 1, difficulty: "elit" },
  { word: "Prokrastinera", options: ["Arbeta snabbt och beslutsamt i tid", "Skjuta upp och dra ut på viktiga uppgifter", "Överträffa sina deadlines", "Avstå från uppgiften helt"], correct: 1, difficulty: "elit" },
  { word: "Sisyfoisk", options: ["Snabbt avklarad och lönande", "Evig, tung och till synes meningslös ansträngning", "Enkel och utan motstånd", "Kortvarig och behaglig"], correct: 1, difficulty: "elit" },
  { word: "Entropi", options: ["Mått på ordning och struktur", "Mått på oordning eller grad av slumpmässighet i ett system", "En enhet för temperatur", "En konstant för tyngdkraft"], correct: 1, difficulty: "elit" },
  { word: "Hegemoni", options: ["Fullständig jämlikhet mellan parter", "Dominerande herravälde över andra", "Frivillig underkastelse", "Splittrad maktlöshet"], correct: 1, difficulty: "elit" },
  { word: "Syllogism", options: ["Ett utropande av en känsla", "En formell logisk slutledning från premisser till slutsats", "En lös association", "En visuell symbolik"], correct: 1, difficulty: "elit" },
  { word: "Tautologi", options: ["En givande ny iakttagelse", "En onödig upprepning av samma innebörd med olika ord", "En tydlig motsägelse", "En kortfattad sammanfattning"], correct: 1, difficulty: "elit" },
  { word: "Metafysisk", options: ["Knuten till det strikt mätbara", "Som rör verkligheten bortom det fysiskt iakttagbara", "Rent materiell till sin natur", "Tekniskt och ingenjörsmässig"], correct: 1, difficulty: "elit" },
  { word: "Idiosynkrasi", options: ["En allmänt utbredd vana", "En mycket personlig egenhet eller säregen reaktion", "En strikt logisk regel", "En objektiv naturlag"], correct: 1, difficulty: "elit" },
  { word: "Hybris", options: ["Dämpad självinsikt", "Övermod som föregår och framkallar ett fall", "Sund självkänsla", "Förkrympt självbild"], correct: 1, difficulty: "elit" },
  { word: "Katalysator", options: ["En kraft som stannar upp ett förlopp", "En utlösande faktor som påskyndar något utan att själv förbrukas", "En slumpmässig biprodukt", "Ett passivt hinder"], correct: 1, difficulty: "elit" },
  { word: "Paradigmskifte", options: ["En mindre justering av detaljer", "Ett grundläggande byte av tankeram eller förståelsemodell", "En kortvarig trend", "En ytlig nyans"], correct: 1, difficulty: "elit" },
  { word: "Oxymoron", options: ["Ett längre resonemang", "En sammanställning av två ord som motsäger varandra", "En upprepning av samma ord", "Ett rent fonetiskt rim"], correct: 1, difficulty: "elit" },
  { word: "Katarsis", options: ["En ytlig tillfällig förströelse", "En renande befrielse efter djup känslomässig upplevelse", "En kall intellektuell analys", "En formell ceremoni utan känsla"], correct: 1, difficulty: "elit" },
  { word: "Synkretism", options: ["Avgränsning till en enda tradition", "Sammansmältning av element från skilda traditioner", "Strikt rensning av influenser", "Aktiv strid mellan läror"], correct: 1, difficulty: "elit" },
  { word: "Dikotomi", options: ["En glidande skala med gradvisa steg", "En skarp uppdelning i två oförenliga delar", "En flerdelad struktur", "En cirkelformad helhet"], correct: 1, difficulty: "elit" },
  { word: "Palimpsest", options: ["Ett helt nyskrivet dokument", "En skriftyta där äldre text skrapats bort och ny skrivits över", "En exakt kopia av ett original", "En tom pergamentrulle"], correct: 1, difficulty: "elit" },
  { word: "Demagog", options: ["En saklig debattör", "En folkuppviglare som spelar på massans känslor", "En tystlåten filosof", "En neutral medlare"], correct: 1, difficulty: "elit" },
  { word: "Epifani", options: ["En långsam gradvis inlärning", "En plötslig och klar insikt eller uppenbarelse", "En ytlig iakttagelse", "En noggrant planerad slutsats"], correct: 1, difficulty: "elit" },
  { word: "Obsolet", options: ["Modernt aktuell", "Föråldrad och inte längre i bruk", "Nyligen uppfunnen", "Tillfälligt ur drift"], correct: 1, difficulty: "elit" },
  { word: "Nepotism", options: ["Opartisk meritbaserad urvalsprocess", "Gynnande av släktingar eller närstående på andras bekostnad", "Rättvis konkurrens", "Strikt byråkratisk rutin"], correct: 1, difficulty: "elit" },
  { word: "Polyvalent", options: ["Endast dugligt för ett syfte", "Användbart i flera olika roller och sammanhang", "Helt obrukbart", "Strikt specialiserat"], correct: 1, difficulty: "elit" },
  { word: "Solipsism", options: ["Tron på en gemensam objektiv värld", "Uppfattningen att endast det egna jaget kan vara säkert existerande", "En kollektivistisk lära", "En materialistisk lära"], correct: 1, difficulty: "elit" },
  { word: "Autarki", options: ["Total beroendeställning", "Fullständig självförsörjning utan utbyte med omvärlden", "Öppen handel med alla", "Militärt beroende"], correct: 1, difficulty: "elit" },
  { word: "Mimesis", options: ["Originellt skapande utan förlagor", "Efterliknande eller avbildning av verkligheten", "Abstrakt spekulation", "Förstörelse av förlagor"], correct: 1, difficulty: "elit" },
  { word: "Proleptisk", options: ["Som enbart ser bakåt", "Som föregriper eller förutser något som ska komma", "Som står stilla i nuet", "Som saknar tidsaspekt"], correct: 1, difficulty: "elit" },
  { word: "Elyseisk", options: ["Dyster och skräckinjagande", "Himmelskt lycksalig och saligt skön", "Helt vardaglig", "Fattig och armodspräglad"], correct: 1, difficulty: "elit" },
  { word: "Ikonoklast", options: ["Någon som bevarar alla traditioner orörda", "Någon som ifrågasätter och bryter ned vedertagna idoler eller normer", "Någon som slaviskt imiterar andra", "Någon som undviker alla ställningstaganden"], correct: 1, difficulty: "elit" },
  { word: "Zeitgeist", options: ["En individuell personlighetsdrag", "Den rådande tidsandan eller epokens präglande stämning", "En fysisk geografisk plats", "En enskild ekonomisk indikator"], correct: 1, difficulty: "elit" },
  { word: "Agnostisk", options: ["Säker på en viss trosuppfattning", "Av uppfattningen att frågan inte kan avgöras med visshet", "Aktivt förnekande", "Strikt religiös"], correct: 1, difficulty: "elit" },
  { word: "Reifiera", options: ["Lösa upp ett konkret ting", "Göra ett abstrakt begrepp till ett till synes konkret ting", "Förneka något helt", "Endast beskriva ytligt"], correct: 1, difficulty: "elit" },
  { word: "Nihilism", options: ["Övertygelse om djupa meningsbärande värden", "Uppfattningen att inga verkliga värden eller meningar finns", "En optimistisk livssyn", "En strängt religiös lära"], correct: 1, difficulty: "elit" }

];
