/* Frågedata för HP Ordquiz
   Varje fråga har: word, options (4 synonymord), correct-index, difficulty.
   Alternativ kan ha en valfri "hint" — en kort förklaring som visas
   när användaren trycker på pilknappen bredvid alternativet.
   Hints läggs både på rätta svar och på svåra distraktor-ord, så att
   pilen fungerar som ordbok — inte som en signal om vilket svar som är rätt.
   Fördelning: grund 70, medel 55, svår 55, elit 40 — totalt 220 ord */
const questions = [

  // === GRUNDNIVÅ (70 ord) ===
  { word: "Aberration", options: [{ text: "Förbättring" }, { text: "Avvikelse" }, { text: "Förklaring" }, { text: "Upprepning" }], correct: 1, difficulty: "grund" },
  { word: "Ambivalent", options: [{ text: "Övertygad" }, { text: "Likgiltig" }, { text: "Negativ" }, { text: "Kluven" }], correct: 3, difficulty: "grund" },
  { word: "Arbiträr", options: [{ text: "Godtycklig" }, { text: "Rättvis" }, { text: "Uträknad" }, { text: "Naturlig" }], correct: 0, difficulty: "grund" },
  { word: "Koncis", options: [{ text: "Otydlig" }, { text: "Kortfattad" }, { text: "Omständlig", hint: "Långrandig och utsvävande" }, { text: "Uttömmande" }], correct: 1, difficulty: "grund" },
  { word: "Obskyr", options: [{ text: "Välkänd" }, { text: "Enkel" }, { text: "Dunkel", hint: "Mörk och svår att förstå" }, { text: "Ytlig", hint: "Bara på ytan utan djup" }], correct: 2, difficulty: "grund" },
  { word: "Preliminär", options: [{ text: "Slutgiltig" }, { text: "Tillfällig" }, { text: "Felaktig" }, { text: "Försenad" }], correct: 1, difficulty: "grund" },
  { word: "Subtil", options: [{ text: "Tydlig" }, { text: "Svag" }, { text: "Finstämd", hint: "Nätt och känslig, svår att lägga märke till" }, { text: "Enkel" }], correct: 2, difficulty: "grund" },
  { word: "Vederlägga", options: [{ text: "Bekräfta" }, { text: "Förklara" }, { text: "Motbevisa" }, { text: "Förstärka" }], correct: 2, difficulty: "grund" },
  { word: "Resignerad", options: [{ text: "Arg" }, { text: "Uppgiven" }, { text: "Förvirrad" }, { text: "Stolt" }], correct: 1, difficulty: "grund" },
  { word: "Tvetydig", options: [{ text: "Entydig" }, { text: "Klar" }, { text: "Osäker" }, { text: "Dubbeltydig" }], correct: 3, difficulty: "grund" },
  { word: "Fatal", options: [{ text: "Ofarlig" }, { text: "Ödesdiger", hint: "Får allvarliga följder" }, { text: "Effektiv" }, { text: "Flyktig", hint: "Snabbt övergående utan att lämna spår" }], correct: 1, difficulty: "grund" },
  { word: "Frugal", options: [{ text: "Slösaktig" }, { text: "Sparsam" }, { text: "Överflödande" }, { text: "Generös" }], correct: 1, difficulty: "grund" },
  { word: "Explicit", options: [{ text: "Antydd" }, { text: "Uttalad" }, { text: "Hemlig" }, { text: "Dold" }], correct: 1, difficulty: "grund" },
  { word: "Indikativ", options: [{ text: "Riktningslös" }, { text: "Slutgiltig" }, { text: "Antydande" }, { text: "Slumpmässig" }], correct: 2, difficulty: "grund" },
  { word: "Legitim", options: [{ text: "Laglig" }, { text: "Falsk" }, { text: "Dold" }, { text: "Tillfällig" }], correct: 0, difficulty: "grund" },
  { word: "Restriktiv", options: [{ text: "Fri" }, { text: "Begränsande" }, { text: "Mild" }, { text: "Växlande" }], correct: 1, difficulty: "grund" },
  { word: "Hypotetisk", options: [{ text: "Verklig" }, { text: "Tänkt" }, { text: "Slumpmässig" }, { text: "Slutlig" }], correct: 1, difficulty: "grund" },
  { word: "Notorisk", options: [{ text: "Okänd" }, { text: "Ökänd" }, { text: "Nyupptäckt" }, { text: "Tillfällig" }], correct: 1, difficulty: "grund" },
  { word: "Paradoxal", options: [{ text: "Logisk" }, { text: "Motsägelsefull" }, { text: "Enkel" }, { text: "Självklar" }], correct: 1, difficulty: "grund" },
  { word: "Destruktiv", options: [{ text: "Uppbyggande" }, { text: "Nedbrytande" }, { text: "Effektiv" }, { text: "Mild" }], correct: 1, difficulty: "grund" },
  { word: "Klandervärd", options: [{ text: "Berömvärd" }, { text: "Förtjänstfull", hint: "Värd att hedras för sin insats" }, { text: "Kritikvärd" }, { text: "Neutral" }], correct: 2, difficulty: "grund" },
  { word: "Försumlig", options: [{ text: "Noggrann" }, { text: "Slarvig" }, { text: "Effektiv" }, { text: "Engagerad" }], correct: 1, difficulty: "grund" },
  { word: "Underminera", options: [{ text: "Förstärka" }, { text: "Försvaga" }, { text: "Bygga upp" }, { text: "Skydda" }], correct: 1, difficulty: "grund" },
  { word: "Hävdvunnen", options: [{ text: "Obeprövad", hint: "Inte ännu satt på prov" }, { text: "Tillfällig" }, { text: "Traditionell" }, { text: "Slumpmässig" }], correct: 2, difficulty: "grund" },
  { word: "Oförvitlig", options: [{ text: "Skyldig" }, { text: "Felfri" }, { text: "Otydlig" }, { text: "Udda" }], correct: 1, difficulty: "grund" },
  { word: "Tillstymmelse", options: [{ text: "Avslut" }, { text: "Antydan", hint: "Försiktig vink utan att säga rakt ut" }, { text: "Problem" }, { text: "Resultat" }], correct: 1, difficulty: "grund" },
  { word: "Uppfordrande", options: [{ text: "Försynt", hint: "Tillbakadragen och blygsam" }, { text: "Manande", hint: "Som uppmanar och kräver handling" }, { text: "Otydlig" }, { text: "Passiv" }], correct: 1, difficulty: "grund" },
  { word: "Förespegla", options: [{ text: "Avslöja" }, { text: "Beskriva" }, { text: "Inbilla", hint: "Få någon att tro något falskt" }, { text: "Förklara" }], correct: 2, difficulty: "grund" },
  { word: "Konsekvent", options: [{ text: "Ologisk" }, { text: "Följdriktig", hint: "Som följer logiskt utan avsteg" }, { text: "Slumpmässig" }, { text: "Skiftande", hint: "Som ändras gång på gång utan mönster" }], correct: 1, difficulty: "grund" },
  { word: "Temporär", options: [{ text: "Bestående" }, { text: "Tillfällig" }, { text: "Hastig" }, { text: "Krävande" }], correct: 1, difficulty: "grund" },
  { word: "Divergerande", options: [{ text: "Sammanlöpande", hint: "Som strömmar ihop mot en gemensam punkt" }, { text: "Åtskiljande", hint: "Som drar åt olika håll" }, { text: "Identisk" }, { text: "Övergående" }], correct: 1, difficulty: "grund" },
  { word: "Fundamental", options: [{ text: "Ytlig" }, { text: "Grundläggande" }, { text: "Tillfällig" }, { text: "Svår" }], correct: 1, difficulty: "grund" },
  { word: "Marginell", options: [{ text: "Central" }, { text: "Obetydlig" }, { text: "Tydlig" }, { text: "Stor" }], correct: 1, difficulty: "grund" },
  { word: "Kompromiss", options: [{ text: "Konflikt" }, { text: "Uppgörelse" }, { text: "Problem" }, { text: "Slutlösning" }], correct: 1, difficulty: "grund" },
  { word: "Analog", options: [{ text: "Liknande" }, { text: "Olik" }, { text: "Slumpmässig" }, { text: "Övergående" }], correct: 0, difficulty: "grund" },
  { word: "Distanserad", options: [{ text: "Nära" }, { text: "Avståndstagande" }, { text: "Framfusig", hint: "Påflugen och taktlös i sitt sätt" }, { text: "Hjärtlig" }], correct: 1, difficulty: "grund" },
  { word: "Progressiv", options: [{ text: "Bakåtsträvande" }, { text: "Framåtsträvande" }, { text: "Stillastående" }, { text: "Växlande" }], correct: 1, difficulty: "grund" },
  { word: "Evident", options: [{ text: "Dold" }, { text: "Uppenbar" }, { text: "Hemlig" }, { text: "Krävande" }], correct: 1, difficulty: "grund" },
  { word: "Relativ", options: [{ text: "Absolut" }, { text: "Sammanhangsberoende" }, { text: "Föränderlig" }, { text: "Självklar" }], correct: 1, difficulty: "grund" },
  { word: "Generös", options: [{ text: "Snål" }, { text: "Frikostig" }, { text: "Otydlig" }, { text: "Avståndstagande" }], correct: 1, difficulty: "grund" },
  { word: "Kritisk", options: [{ text: "Accepterande" }, { text: "Granskande" }, { text: "Stressad" }, { text: "Neutral" }], correct: 1, difficulty: "grund" },
  { word: "Abstrakt", options: [{ text: "Konkret" }, { text: "Teoretisk" }, { text: "Enkel" }, { text: "Flyktig" }], correct: 1, difficulty: "grund" },
  { word: "Konventionell", options: [{ text: "Avvikande" }, { text: "Traditionell" }, { text: "Slumpmässig" }, { text: "Nyskapande" }], correct: 1, difficulty: "grund" },
  { word: "Ambitiös", options: [{ text: "Lat" }, { text: "Målmedveten" }, { text: "Oövertänkt" }, { text: "Otydlig" }], correct: 1, difficulty: "grund" },
  { word: "Exkludera", options: [{ text: "Inkludera" }, { text: "Utesluta" }, { text: "Förklara" }, { text: "Förstärka" }], correct: 1, difficulty: "grund" },
  { word: "Eliminera", options: [{ text: "Skapa" }, { text: "Avlägsna" }, { text: "Förklara" }, { text: "Öka" }], correct: 1, difficulty: "grund" },
  { word: "Dominera", options: [{ text: "Underordna" }, { text: "Behärska" }, { text: "Försvaga" }, { text: "Krympa" }], correct: 1, difficulty: "grund" },
  { word: "Konsekvens", options: [{ text: "Orsak" }, { text: "Följd" }, { text: "Problem" }, { text: "Slumpinslag" }], correct: 1, difficulty: "grund" },
  { word: "Neutral", options: [{ text: "Partisk" }, { text: "Opartisk" }, { text: "Inblandad" }, { text: "Växlande" }], correct: 1, difficulty: "grund" },
  { word: "Ignorera", options: [{ text: "Uppmärksamma" }, { text: "Strunta i" }, { text: "Förstå" }, { text: "Förklara" }], correct: 1, difficulty: "grund" },
  { word: "Kontradiktion", options: [{ text: "Likhet" }, { text: "Motsägelse" }, { text: "Problem" }, { text: "Förklaring" }], correct: 1, difficulty: "grund" },
  { word: "Preciserad", options: [{ text: "Vag" }, { text: "Specificerad" }, { text: "Hastig" }, { text: "Tillfällig" }], correct: 1, difficulty: "grund" },
  { word: "Reducera", options: [{ text: "Öka" }, { text: "Minska" }, { text: "Förklara" }, { text: "Skapa" }], correct: 1, difficulty: "grund" },
  { word: "Exponera", options: [{ text: "Dölja" }, { text: "Blotta", hint: "Visa upp eller avslöja" }, { text: "Förklara" }, { text: "Skydda" }], correct: 1, difficulty: "grund" },
  { word: "Komplex", options: [{ text: "Enkel" }, { text: "Invecklad" }, { text: "Hastig" }, { text: "Genomskinlig" }], correct: 1, difficulty: "grund" },
  { word: "Stabil", options: [{ text: "Svajig" }, { text: "Stadig" }, { text: "Snabb" }, { text: "Komplicerad" }], correct: 1, difficulty: "grund" },
  { word: "Flexibel", options: [{ text: "Stel" }, { text: "Anpassningsbar" }, { text: "Snabb" }, { text: "Otydlig" }], correct: 1, difficulty: "grund" },
  { word: "Permanent", options: [{ text: "Tillfällig" }, { text: "Varaktig" }, { text: "Hastig" }, { text: "Otydlig" }], correct: 1, difficulty: "grund" },
  { word: "Approximation", options: [{ text: "Exakthet" }, { text: "Uppskattning" }, { text: "Problem" }, { text: "Slutlösning" }], correct: 1, difficulty: "grund" },
  { word: "Kapitulera", options: [{ text: "Stå på sig" }, { text: "Ge upp" }, { text: "Ifrågasätta" }, { text: "Förhandla" }], correct: 1, difficulty: "grund" },
  { word: "Motvillig", options: [{ text: "Ivrig" }, { text: "Ovillig" }, { text: "Vägrande" }, { text: "Entusiastisk" }], correct: 1, difficulty: "grund" },
  { word: "Signifikant", options: [{ text: "Obetydlig" }, { text: "Betydelsefull" }, { text: "Slumpmässig" }, { text: "Oklar" }], correct: 1, difficulty: "grund" },
  { word: "Rigorös", options: [{ text: "Slapp" }, { text: "Sträng" }, { text: "Flexibel" }, { text: "Ytlig" }], correct: 1, difficulty: "grund" },
  { word: "Prioritera", options: [{ text: "Likabehandla" }, { text: "Välja först" }, { text: "Skjuta upp" }, { text: "Avstå" }], correct: 1, difficulty: "grund" },
  { word: "Kulminera", options: [{ text: "Starta svagt" }, { text: "Nå toppen" }, { text: "Avta" }, { text: "Stå stilla" }], correct: 1, difficulty: "grund" },
  { word: "Trivial", options: [{ text: "Djup" }, { text: "Obetydlig" }, { text: "Allvarlig" }, { text: "Oersättlig" }], correct: 1, difficulty: "grund" },
  { word: "Ikonisk", options: [{ text: "Okänd" }, { text: "Symbolisk" }, { text: "Ny" }, { text: "Otydlig" }], correct: 1, difficulty: "grund" },
  { word: "Autentisk", options: [{ text: "Förfalskad" }, { text: "Äkta" }, { text: "Kopierad" }, { text: "Otydlig" }], correct: 1, difficulty: "grund" },
  { word: "Disträ", options: [{ text: "Fokuserad" }, { text: "Tankspridd" }, { text: "Noggrann" }, { text: "Stressad" }], correct: 1, difficulty: "grund" },
  { word: "Omdiskuterad", options: [{ text: "Erkänd" }, { text: "Kontroversiell", hint: "Som väcker skilda åsikter och debatt" }, { text: "Okänd" }, { text: "Tillfällig" }], correct: 1, difficulty: "grund" },

  // === MEDELNIVÅ (55 ord) ===
  { word: "Lakonisk", options: [{ text: "Utförlig" }, { text: "Kortfattad" }, { text: "Otydlig" }, { text: "Hånfull" }], correct: 1, difficulty: "medel" },
  { word: "Repressiv", options: [{ text: "Frigörande" }, { text: "Förtryckande" }, { text: "Tillfällig" }, { text: "Opartisk" }], correct: 1, difficulty: "medel" },
  { word: "Sporadisk", options: [{ text: "Regelbunden" }, { text: "Oregelbunden" }, { text: "Ständig" }, { text: "Avgörande" }], correct: 1, difficulty: "medel" },
  { word: "Pragmatisk", options: [{ text: "Teoretisk" }, { text: "Praktisk" }, { text: "Känslostyrd" }, { text: "Traditionsbunden" }], correct: 1, difficulty: "medel" },
  { word: "Dogmatisk", options: [{ text: "Öppen" }, { text: "Orubblig", hint: "Låst fast vid en lära utan omprövning" }, { text: "Tvivlande" }, { text: "Prövande", hint: "Försöksvis testande utan låsta åsikter" }], correct: 1, difficulty: "medel" },
  { word: "Eklektisk", options: [{ text: "Enhetlig" }, { text: "Sammansatt", hint: "Hopplockad från många olika håll" }, { text: "Originell" }, { text: "Motsägande", hint: "Som strider mot sig själv eller varandra" }], correct: 1, difficulty: "medel" },
  { word: "Empirisk", options: [{ text: "Teoretisk" }, { text: "Erfarenhetsbaserad" }, { text: "Spekulativ", hint: "Bygger på antaganden snarare än fakta" }, { text: "Traditionell" }], correct: 1, difficulty: "medel" },
  { word: "Nominell", options: [{ text: "Reell", hint: "Faktisk och konkret, inte bara på papperet" }, { text: "Skenbar", hint: "Verkar vara det — men är det inte i praktiken" }, { text: "Överlägsen" }, { text: "Uträknad" }], correct: 1, difficulty: "medel" },
  { word: "Altruistisk", options: [{ text: "Självisk" }, { text: "Osjälvisk" }, { text: "Likgiltig" }, { text: "Beräknande" }], correct: 1, difficulty: "medel" },
  { word: "Stringent", options: [{ text: "Lös" }, { text: "Strikt", hint: "Strikt logiskt följdriktig" }, { text: "Känslostyrd" }, { text: "Öppen" }], correct: 1, difficulty: "medel" },
  { word: "Ortodox", options: [{ text: "Avvikande" }, { text: "Traditionstrogen" }, { text: "Tveksam" }, { text: "Nyskapande" }], correct: 1, difficulty: "medel" },
  { word: "Symbios", options: [{ text: "Ensidighet" }, { text: "Samverkan" }, { text: "Konflikt" }, { text: "Tillfällighet" }], correct: 1, difficulty: "medel" },
  { word: "Reciprok", options: [{ text: "Ensidig" }, { text: "Ömsesidig" }, { text: "Växlande" }, { text: "Likgiltig" }], correct: 1, difficulty: "medel" },
  { word: "Oförbehållsam", options: [{ text: "Reserverad", hint: "Avvaktande och tillbakadragen" }, { text: "Helhjärtad" }, { text: "Tveksam" }, { text: "Hemlighetsfull" }], correct: 1, difficulty: "medel" },
  { word: "Unison", options: [{ text: "Splittrad" }, { text: "Enstämmig", hint: "I samklang, med en röst" }, { text: "Konfliktfylld" }, { text: "Tillfällig" }], correct: 1, difficulty: "medel" },
  { word: "Kongenial", options: [{ text: "Oförenlig", hint: "Omöjlig att förena utan motsättning" }, { text: "Själsförvant", hint: "Nära besläktad i tanke och känsla" }, { text: "Ytlig" }, { text: "Efterliknad", hint: "Imiterad utan eget original" }], correct: 1, difficulty: "medel" },
  { word: "Exemplarisk", options: [{ text: "Medelmåttig" }, { text: "Föredömlig" }, { text: "Misslyckad" }, { text: "Ordinär", hint: "Helt vanlig och utan särdrag" }], correct: 1, difficulty: "medel" },
  { word: "Prekär", options: [{ text: "Stabil" }, { text: "Vansklig", hint: "Osäker och svårhanterlig" }, { text: "Lösbar" }, { text: "Ovidkommande", hint: "Som inte berör eller är relevant" }], correct: 1, difficulty: "medel" },
  { word: "Reminiscens", options: [{ text: "Nyhet" }, { text: "Minne" }, { text: "Förutsägelse" }, { text: "Bevis" }], correct: 1, difficulty: "medel" },
  { word: "Schablon", options: [{ text: "Originalitet" }, { text: "Stereotyp", hint: "Förenklad mall eller fördom" }, { text: "Konstverk" }, { text: "Detaljplan" }], correct: 1, difficulty: "medel" },
  { word: "Manifestera", options: [{ text: "Dölja" }, { text: "Uppenbara" }, { text: "Ifrågasätta" }, { text: "Upplösa" }], correct: 1, difficulty: "medel" },
  { word: "Polarisera", options: [{ text: "Förena" }, { text: "Splittra" }, { text: "Mjuka upp" }, { text: "Oberöra" }], correct: 1, difficulty: "medel" },
  { word: "Koherens", options: [{ text: "Osammanhang" }, { text: "Sammanhang" }, { text: "Slump" }, { text: "Motsägelse" }], correct: 1, difficulty: "medel" },
  { word: "Implicit", options: [{ text: "Uttalad" }, { text: "Underförstådd" }, { text: "Saknad" }, { text: "Felaktig" }], correct: 1, difficulty: "medel" },
  { word: "Cynisk", options: [{ text: "Naiv" }, { text: "Misstrogen", hint: "Misstänksam mot andras motiv" }, { text: "Entusiastisk" }, { text: "Tveksam" }], correct: 1, difficulty: "medel" },
  { word: "Eufori", options: [{ text: "Dov känsla", hint: "Avtrubbad och dämpad sinnesstämning" }, { text: "Lyckorus", hint: "Översvallande lyckokänsla" }, { text: "Sorg" }, { text: "Likgiltighet" }], correct: 1, difficulty: "medel" },
  { word: "Melankoli", options: [{ text: "Glädje" }, { text: "Svårmod", hint: "Tung, stillsam sorg" }, { text: "Ilska" }, { text: "Neutralitet" }], correct: 1, difficulty: "medel" },
  { word: "Apati", options: [{ text: "Engagemang" }, { text: "Liknöjdhet", hint: "Likgiltig brist på engagemang" }, { text: "Ilska" }, { text: "Uppmärksamhet" }], correct: 1, difficulty: "medel" },
  { word: "Pedantisk", options: [{ text: "Lättsinnig" }, { text: "Petig" }, { text: "Kreativ" }, { text: "Slarvig" }], correct: 1, difficulty: "medel" },
  { word: "Tendentiös", options: [{ text: "Neutral" }, { text: "Vinklad" }, { text: "Budskapslös" }, { text: "Vetenskaplig" }], correct: 1, difficulty: "medel" },
  { word: "Inkorporera", options: [{ text: "Utesluta" }, { text: "Införliva", hint: "Göra till en del av helheten" }, { text: "Förbjuda" }, { text: "Separera" }], correct: 1, difficulty: "medel" },
  { word: "Appellera", options: [{ text: "Avvisa" }, { text: "Vädja" }, { text: "Lyssna" }, { text: "Upprepa" }], correct: 1, difficulty: "medel" },
  { word: "Antydan", options: [{ text: "Påstående" }, { text: "Vink", hint: "Försiktig hänvisning utan att säga rakt ut" }, { text: "Konfrontation" }, { text: "Beskrivning" }], correct: 1, difficulty: "medel" },
  { word: "Skepsis", options: [{ text: "Tilltro" }, { text: "Tvivel" }, { text: "Accept" }, { text: "Likgiltighet" }], correct: 1, difficulty: "medel" },
  { word: "Diametral", options: [{ text: "Liknande" }, { text: "Motsatt" }, { text: "Överlappande" }, { text: "Otydlig" }], correct: 1, difficulty: "medel" },
  { word: "Vokal", options: [{ text: "Tyst" }, { text: "Högröstad", hint: "Som hörs tydligt och tar plats" }, { text: "Skriftlig" }, { text: "Dold" }], correct: 1, difficulty: "medel" },
  { word: "Latent", options: [{ text: "Aktiv" }, { text: "Dold" }, { text: "Upplöst" }, { text: "Överdriven" }], correct: 1, difficulty: "medel" },
  { word: "Profan", options: [{ text: "Helig" }, { text: "Världslig" }, { text: "Mystisk" }, { text: "Rituell" }], correct: 1, difficulty: "medel" },
  { word: "Eminent", options: [{ text: "Medelmåttig" }, { text: "Framstående" }, { text: "Tillfällig" }, { text: "Anonym" }], correct: 1, difficulty: "medel" },
  { word: "Eterisk", options: [{ text: "Jordnära", hint: "Med båda fötterna stadigt på marken" }, { text: "Svävande", hint: "Lätt och luftig, nästan andlig" }, { text: "Grov" }, { text: "Färglös" }], correct: 1, difficulty: "medel" },
  { word: "Dekadent", options: [{ text: "Blomstrande" }, { text: "Nedgången", hint: "I förfall efter en bättre tid" }, { text: "Oförändrad" }, { text: "Nyuppkommen", hint: "Nyligen uppstått, utan föregående tradition" }], correct: 1, difficulty: "medel" },
  { word: "Obönhörlig", options: [{ text: "Eftergivlig", hint: "Lättpåverkad och böjlig" }, { text: "Obeveklig", hint: "Skoningslös, omöjlig att beveka" }, { text: "Mild" }, { text: "Tveksam" }], correct: 1, difficulty: "medel" },
  { word: "Kallsinnig", options: [{ text: "Medkännande" }, { text: "Känslokall" }, { text: "Passionerad" }, { text: "Osäker" }], correct: 1, difficulty: "medel" },
  { word: "Oblyg", options: [{ text: "Försynt", hint: "Tillbakadragen och blygsam" }, { text: "Fräck" }, { text: "Mjuk" }, { text: "Rädd" }], correct: 1, difficulty: "medel" },
  { word: "Tarvlig", options: [{ text: "Elegant" }, { text: "Vulgär", hint: "Simpel och smaklös" }, { text: "Storslagen" }, { text: "Utsökt", hint: "Förfinat smakfull och raffinerad" }], correct: 1, difficulty: "medel" },
  { word: "Förhärligande", options: [{ text: "Nedsättande" }, { text: "Lovprisande" }, { text: "Nyktert" }, { text: "Kritiserande" }], correct: 1, difficulty: "medel" },
  { word: "Fragmentarisk", options: [{ text: "Helgjuten", hint: "Samlad och utan brott" }, { text: "Splittrad" }, { text: "Uttömmande" }, { text: "Enhetlig" }], correct: 1, difficulty: "medel" },
  { word: "Homogen", options: [{ text: "Enhetlig" }, { text: "Blandad" }, { text: "Motstridig" }, { text: "Obestämd" }], correct: 0, difficulty: "medel" },
  { word: "Heterogen", options: [{ text: "Enhetlig" }, { text: "Blandad" }, { text: "Tom" }, { text: "Sammanhållen" }], correct: 1, difficulty: "medel" },
  { word: "Reservation", options: [{ text: "Uppslutning" }, { text: "Förbehåll", hint: "Invändning eller villkor" }, { text: "Bekräftelse" }, { text: "Observation" }], correct: 1, difficulty: "medel" },
  { word: "Hedonistisk", options: [{ text: "Försakande", hint: "Som avstår från lust och bekvämlighet" }, { text: "Njutningsinriktad" }, { text: "Likgiltig" }, { text: "Pliktinriktad" }], correct: 1, difficulty: "medel" },
  { word: "Oroväckande", options: [{ text: "Lugnande" }, { text: "Oroande" }, { text: "Neutralt" }, { text: "Uppmuntrande" }], correct: 1, difficulty: "medel" },
  { word: "Översiktlig", options: [{ text: "Detaljerad" }, { text: "Sammanfattande" }, { text: "Rörig" }, { text: "Specifik" }], correct: 1, difficulty: "medel" },
  { word: "Oavsiktlig", options: [{ text: "Planerad" }, { text: "Omedveten" }, { text: "Uttalad" }, { text: "Övad" }], correct: 1, difficulty: "medel" },
  { word: "Ymnig", options: [{ text: "Knapp" }, { text: "Riklig" }, { text: "Jämn" }, { text: "Sällsynt" }], correct: 1, difficulty: "medel" },

  // === SVÅR NIVÅ (55 ord) ===
  { word: "Asketisk", options: [{ text: "Livsnjutande" }, { text: "Avhållsam", hint: "Avstår från njutningar och bekvämlighet" }, { text: "Fåfäng" }, { text: "Utsvävande", hint: "Med njutningar bortom det måttliga" }], correct: 1, difficulty: "svar" },
  { word: "Stipulera", options: [{ text: "Antyda", hint: "Försiktigt anspela utan att säga rakt ut" }, { text: "Föreskriva", hint: "Uttryckligen fastställa som krav" }, { text: "Upphäva" }, { text: "Ignorera" }], correct: 1, difficulty: "svar" },
  { word: "Emfatisk", options: [{ text: "Försiktig" }, { text: "Eftertrycklig", hint: "Sagt med starkt eftertryck" }, { text: "Antydd" }, { text: "Obetonad", hint: "Sagt utan särskild tonvikt" }], correct: 1, difficulty: "svar" },
  { word: "Vigilant", options: [{ text: "Slö" }, { text: "Vaksam" }, { text: "Distraherad" }, { text: "Godtrogen", hint: "Lättlurad av andras påståenden" }], correct: 1, difficulty: "svar" },
  { word: "Bombastisk", options: [{ text: "Saklig" }, { text: "Pompös", hint: "Skrytsamt högtravande" }, { text: "Kortfattad" }, { text: "Diskret", hint: "Försynt nedtonad utan att ta plats" }], correct: 1, difficulty: "svar" },
  { word: "Obskurantism", options: [{ text: "Kunskapsiver", hint: "Brinnande vilja att söka och dela kunskap" }, { text: "Upplysningsmotstånd", hint: "Motstånd mot upplysning och kritiskt tänkande" }, { text: "Vetenskapstro" }, { text: "Öppenhet" }], correct: 1, difficulty: "svar" },
  { word: "Konfabulera", options: [{ text: "Minnas rätt" }, { text: "Fantisera", hint: "Hitta på minnen som känns äkta" }, { text: "Glömma" }, { text: "Förneka" }], correct: 1, difficulty: "svar" },
  { word: "Obfuskera", options: [{ text: "Klargöra" }, { text: "Fördunkla", hint: "Göra avsiktligt otydligt" }, { text: "Summera" }, { text: "Förenkla" }], correct: 1, difficulty: "svar" },
  { word: "Hypostasera", options: [{ text: "Upplösa" }, { text: "Förtingliga", hint: "Behandla något abstrakt som om det vore ett ting" }, { text: "Bevisa" }, { text: "Spekulera", hint: "Utveckla teorier utan stöd i fakta" }], correct: 1, difficulty: "svar" },
  { word: "Paradigmatisk", options: [{ text: "Avvikande" }, { text: "Mönstergill", hint: "Fullständigt föredömlig inom sitt fält" }, { text: "Marginell" }, { text: "Föråldrad", hint: "Tillhör en svunnen tid utan aktualitet" }], correct: 1, difficulty: "svar" },
  { word: "Apokryfisk", options: [{ text: "Dokumenterad" }, { text: "Oäkta", hint: "Av tvivelaktig äkthet eller ursprung" }, { text: "Erkänd" }, { text: "Obeprövad", hint: "Inte ännu satt på prov" }], correct: 1, difficulty: "svar" },
  { word: "Sofistikerad", options: [{ text: "Okonstlad", hint: "Naturlig och utan tillgjordhet" }, { text: "Förfinad" }, { text: "Rå" }, { text: "Primitiv" }], correct: 1, difficulty: "svar" },
  { word: "Emanera", options: [{ text: "Absorbera", hint: "Suga upp och ta in i sig" }, { text: "Utstråla", hint: "Strömma ut eller utgå från en källa" }, { text: "Stillna" }, { text: "Upplösas" }], correct: 1, difficulty: "svar" },
  { word: "Aversion", options: [{ text: "Attraktion" }, { text: "Avsky" }, { text: "Likgiltighet" }, { text: "Nyfikenhet" }], correct: 1, difficulty: "svar" },
  { word: "Introspektion", options: [{ text: "Omvärldsgranskning", hint: "Granskning riktad mot allt utanför en själv" }, { text: "Självrannsakan", hint: "Inre granskning av egna tankar och känslor" }, { text: "Iakttagelse" }, { text: "Utredning" }], correct: 1, difficulty: "svar" },
  { word: "Estetisk", options: [{ text: "Etisk", hint: "Som rör rätt och fel snarare än det sköna" }, { text: "Skönhetsbetonad", hint: "Som rör det sköna och sinnliga" }, { text: "Praktisk" }, { text: "Logisk" }], correct: 1, difficulty: "svar" },
  { word: "Insinuera", options: [{ text: "Öppet anklaga" }, { text: "Anspela", hint: "Antyda nedsättande utan att säga rakt ut" }, { text: "Beskriva sakligt" }, { text: "Smickra", hint: "Berömma överdrivet för att vinna gunst" }], correct: 1, difficulty: "svar" },
  { word: "Diaspora", options: [{ text: "Samlad folkgrupp", hint: "Befolkning som lever på samma plats" }, { text: "Förskingring", hint: "Folkgrupp spridd över flera länder" }, { text: "Ny stat" }, { text: "Tillfällig samling" }], correct: 1, difficulty: "svar" },
  { word: "Nyansera", options: [{ text: "Förenkla" }, { text: "Förfina", hint: "Ge fler bottnar och skiftningar" }, { text: "Förvränga", hint: "Vrida innebörden så att den blir missvisande" }, { text: "Bekräfta" }], correct: 1, difficulty: "svar" },
  { word: "Obstinat", options: [{ text: "Lättledd" }, { text: "Envis" }, { text: "Anpasslig", hint: "Snabb att rätta sig efter andra" }, { text: "Tveksam" }], correct: 1, difficulty: "svar" },
  { word: "Kontemplativ", options: [{ text: "Rastlös" }, { text: "Eftertänksam" }, { text: "Ytlig" }, { text: "Debatterande" }], correct: 1, difficulty: "svar" },
  { word: "Solitär", options: [{ text: "Sällskaplig" }, { text: "Ensam" }, { text: "Grupptillhörande" }, { text: "Avstängd" }], correct: 1, difficulty: "svar" },
  { word: "Ekvivalent", options: [{ text: "Olik" }, { text: "Likvärdig", hint: "Av motsvarande värde" }, { text: "Överlägsen" }, { text: "Tvetydig", hint: "Som kan tolkas på två olika vis" }], correct: 1, difficulty: "svar" },
  { word: "Dispyt", options: [{ text: "Samförstånd" }, { text: "Tvist" }, { text: "Enighet" }, { text: "Observation" }], correct: 1, difficulty: "svar" },
  { word: "Affektation", options: [{ text: "Äkthet" }, { text: "Tillgjordhet", hint: "Konstlat och onaturligt sätt" }, { text: "Uppriktighet", hint: "Att tala och uppträda utan förställning" }, { text: "Neutralitet" }], correct: 1, difficulty: "svar" },
  { word: "Rudimentär", options: [{ text: "Utvecklad" }, { text: "Outvecklad" }, { text: "Komplicerad" }, { text: "Förfallen", hint: "I dåligt skick efter försummelse" }], correct: 1, difficulty: "svar" },
  { word: "Substantiell", options: [{ text: "Obetydlig" }, { text: "Betydande" }, { text: "Kosmetisk", hint: "Endast ytlig, utan att gå på djupet" }, { text: "Oklar" }], correct: 1, difficulty: "svar" },
  { word: "Dilettantisk", options: [{ text: "Mästerlig" }, { text: "Amatörmässig" }, { text: "Exakt" }, { text: "Rutinerad", hint: "Erfaren och säker av lång övning" }], correct: 1, difficulty: "svar" },
  { word: "Opportun", options: [{ text: "Olägligt" }, { text: "Läglig", hint: "Som kommer vid passande tidpunkt" }, { text: "Försent" }, { text: "Ovidkommande", hint: "Utan koppling till saken som behandlas" }], correct: 1, difficulty: "svar" },
  { word: "Kapricios", options: [{ text: "Stadig" }, { text: "Nyckfull", hint: "Oberäknelig och full av infall" }, { text: "Balanserad" }, { text: "Logisk" }], correct: 1, difficulty: "svar" },
  { word: "Diffus", options: [{ text: "Skarp" }, { text: "Otydlig" }, { text: "Fokuserad" }, { text: "Ämnesbunden", hint: "Hållen inom ett bestämt område" }], correct: 1, difficulty: "svar" },
  { word: "Impassibel", options: [{ text: "Känslostark" }, { text: "Oberörd", hint: "Utan yttre tecken på känsla" }, { text: "Upprörd" }, { text: "Sårbar" }], correct: 1, difficulty: "svar" },
  { word: "Inkommensurabel", options: [{ text: "Jämförbar" }, { text: "Ojämförbar", hint: "Omöjlig att jämföra med gemensam måttstock" }, { text: "Mätbar" }, { text: "Likvärdig", hint: "Av motsvarande värde" }], correct: 1, difficulty: "svar" },
  { word: "Insubordination", options: [{ text: "Lydnad" }, { text: "Olydnad", hint: "Vägran att lyda överordnad" }, { text: "Självförsvar" }, { text: "Förhandling" }], correct: 1, difficulty: "svar" },
  { word: "Preludium", options: [{ text: "Upplösning", hint: "Slutlig urladdning där spänningen löses" }, { text: "Förspel", hint: "Inledande del före huvudstycket" }, { text: "Mittdel" }, { text: "Avslutning" }], correct: 1, difficulty: "svar" },
  { word: "Prosaisk", options: [{ text: "Upphöjd", hint: "Höjd över det vardagliga, värdig och formell" }, { text: "Vardaglig", hint: "Enkel och utan poetisk lyftning" }, { text: "Konstnärlig" }, { text: "Känslosam" }], correct: 1, difficulty: "svar" },
  { word: "Nimbus", options: [{ text: "Matthet", hint: "Glanslöst och kraftlöst yttre" }, { text: "Strålglans", hint: "Aura av berömmelse eller helighet" }, { text: "Avgränsning" }, { text: "Detalj" }], correct: 1, difficulty: "svar" },
  { word: "Ostentativ", options: [{ text: "Hemlig" }, { text: "Iögonfallande", hint: "Tydligt visad för att synas" }, { text: "Anspråkslös", hint: "Utan krav på beröm eller uppmärksamhet" }, { text: "Omedveten" }], correct: 1, difficulty: "svar" },
  { word: "Peripeti", options: [{ text: "Rak linje" }, { text: "Vändpunkt", hint: "Avgörande förändring i förloppet" }, { text: "Stillestånd" }, { text: "Nedtrappning", hint: "Gradvis avveckling efter en topp" }], correct: 1, difficulty: "svar" },
  { word: "Elaborera", options: [{ text: "Sammanfatta" }, { text: "Utveckla", hint: "Utöka och förfina i detalj" }, { text: "Kasta" }, { text: "Avsluta" }], correct: 1, difficulty: "svar" },
  { word: "Komplementär", options: [{ text: "Likartad" }, { text: "Kompletterande", hint: "Som fyller ut till en helhet" }, { text: "Oförenlig", hint: "Omöjlig att förena utan motsättning" }, { text: "Överflödig" }], correct: 1, difficulty: "svar" },
  { word: "Inneboende", options: [{ text: "Påklistrad", hint: "Konstlat tillagd utöver det egentliga" }, { text: "Medfödd", hint: "Naturligt tillhörande själva saken" }, { text: "Oförenlig" }, { text: "Lånad" }], correct: 1, difficulty: "svar" },
  { word: "Vexerande", options: [{ text: "Självklart" }, { text: "Förbryllande", hint: "Svårlöst och kluvet för tanken" }, { text: "Betydelselöst" }, { text: "Ordinärt", hint: "Helt vanligt och utan särdrag" }], correct: 1, difficulty: "svar" },
  { word: "Insisterande", options: [{ text: "Eftergivlig", hint: "Snabbt benägen att backa och kompromissa" }, { text: "Ihärdig", hint: "Envist kvarhållande vid sitt anspråk" }, { text: "Slumpmässig" }, { text: "Tillbakadragen" }], correct: 1, difficulty: "svar" },
  { word: "Retorisk", options: [{ text: "Faktaorienterad" }, { text: "Övertygande", hint: "Som rör talekonstens grepp" }, { text: "Matematisk" }, { text: "Tystnadsmässig" }], correct: 1, difficulty: "svar" },
  { word: "Skrupulös", options: [{ text: "Oansvarig" }, { text: "Samvetsgrann", hint: "Mycket noggrann med rätt och fel" }, { text: "Likgiltig" }, { text: "Flyktig", hint: "Snabbt övergående utan att lämna spår" }], correct: 1, difficulty: "svar" },
  { word: "Omen", options: [{ text: "Resultat" }, { text: "Förtecken", hint: "Tecken som varslar om framtiden" }, { text: "Ordinärt" }, { text: "Bevis" }], correct: 1, difficulty: "svar" },
  { word: "Plausibel", options: [{ text: "Orimlig" }, { text: "Trovärdig" }, { text: "Bevisad" }, { text: "Komplicerad" }], correct: 1, difficulty: "svar" },
  { word: "Anomali", options: [{ text: "Bekräftelse" }, { text: "Avvikelse" }, { text: "Följd" }, { text: "Likhet" }], correct: 1, difficulty: "svar" },
  { word: "Prolog", options: [{ text: "Efterord" }, { text: "Inledning" }, { text: "Sammanfattning" }, { text: "Parentes" }], correct: 1, difficulty: "svar" },
  { word: "Konfession", options: [{ text: "Förnekelse" }, { text: "Bekännelse" }, { text: "Motsägelse" }, { text: "Reservation" }], correct: 1, difficulty: "svar" },
  { word: "Panegyrik", options: [{ text: "Kritiktal", hint: "Tal där brister granskas hårt" }, { text: "Lovtal", hint: "Översvallande hyllningstal" }, { text: "Beskrivning" }, { text: "Begravningstal" }], correct: 1, difficulty: "svar" },
  { word: "Dualism", options: [{ text: "Enhet" }, { text: "Tudelning", hint: "Uppdelning i två motverkande principer" }, { text: "Mångfald" }, { text: "Kaos" }], correct: 1, difficulty: "svar" },
  { word: "Akribi", options: [{ text: "Slarv" }, { text: "Exakthet", hint: "Ytterlig noggrannhet och precision" }, { text: "Frihet" }, { text: "Snabbhet" }], correct: 1, difficulty: "svar" },
  { word: "Insensitiv", options: [{ text: "Lyhörd" }, { text: "Okänslig" }, { text: "Empatisk" }, { text: "Reagerande" }], correct: 1, difficulty: "svar" },

  // === ELITNIVÅ (40 ord) ===
  { word: "Heuristik", options: [{ text: "Bevismetod", hint: "Strikt teknik för att slå fast att något är sant" }, { text: "Tumregelmetod", hint: "Upptäcktsmetod som bygger på erfarenhet" }, { text: "Slumpgissning" }, { text: "Bevisprocedur" }], correct: 1, difficulty: "elit" },
  { word: "Ontologisk", options: [{ text: "Grammatisk", hint: "Som rör språkets uppbyggnad och regler" }, { text: "Varandebaserad", hint: "Som rör tillvarons grundläggande natur" }, { text: "Kemisk" }, { text: "Ytlig" }], correct: 1, difficulty: "elit" },
  { word: "Epistemologi", options: [{ text: "Etik", hint: "Läran om rätt och fel handlande" }, { text: "Kunskapsteori", hint: "Läran om kunskapens grund och gränser" }, { text: "Biologi" }, { text: "Konstlära" }], correct: 1, difficulty: "elit" },
  { word: "Teleologisk", options: [{ text: "Slumpstyrd", hint: "Drivs av tillfälligheter utan plan" }, { text: "Ändamålsstyrd", hint: "Styrs av sitt mål eller syfte" }, { text: "Bakåtsträvande" }, { text: "Orsaksblind" }], correct: 1, difficulty: "elit" },
  { word: "Hermeneutik", options: [{ text: "Mekanik" }, { text: "Tolkningslära", hint: "Läran om att tolka texter och meningar" }, { text: "Känslolära", hint: "Lära som fokuserar på känslolivets natur" }, { text: "Strategi" }], correct: 1, difficulty: "elit" },
  { word: "Sofism", options: [{ text: "Sant resonemang" }, { text: "Skenargument", hint: "Verkar riktigt men är vilseledande" }, { text: "Slutledning", hint: "Logiskt steg från premisser till slutsats" }, { text: "Faktum" }], correct: 1, difficulty: "elit" },
  { word: "Sui generis", options: [{ text: "Vanlig" }, { text: "Säregen", hint: "Av sitt eget unika slag utan motsvarighet" }, { text: "Identisk" }, { text: "Typisk" }], correct: 1, difficulty: "elit" },
  { word: "Panacea", options: [{ text: "Gift" }, { text: "Universalmedel", hint: "Medel som sägs bota allt" }, { text: "Salva" }, { text: "Försiktighet" }], correct: 1, difficulty: "elit" },
  { word: "Saturnisk", options: [{ text: "Uppsluppen", hint: "Glad och bekymmersfri till lynnet" }, { text: "Tungsint", hint: "Dyster och grubblande till lynnet" }, { text: "Glättig" }, { text: "Aggressiv" }], correct: 1, difficulty: "elit" },
  { word: "Prokrastinera", options: [{ text: "Arbeta snabbt" }, { text: "Senarelägga", hint: "Skjuta upp viktiga uppgifter" }, { text: "Överträffa" }, { text: "Avstå helt" }], correct: 1, difficulty: "elit" },
  { word: "Sisyfoisk", options: [{ text: "Lönande" }, { text: "Fruktlös", hint: "Evig och till synes meningslös ansträngning" }, { text: "Enkel" }, { text: "Kortvarig" }], correct: 1, difficulty: "elit" },
  { word: "Entropi", options: [{ text: "Ordningsmått", hint: "Mått på hur strukturerat ett system är" }, { text: "Oordningsmått", hint: "Mått på slumpmässighet i ett system" }, { text: "Temperaturmått" }, { text: "Tyngdkonstant" }], correct: 1, difficulty: "elit" },
  { word: "Hegemoni", options: [{ text: "Jämlikhet" }, { text: "Herravälde", hint: "Dominerande maktställning över andra" }, { text: "Underkastelse", hint: "Att foga sig under en överordnad makt" }, { text: "Maktlöshet" }], correct: 1, difficulty: "elit" },
  { word: "Syllogism", options: [{ text: "Utrop" }, { text: "Slutledning", hint: "Logisk härledning från premisser till slutsats" }, { text: "Association", hint: "Tankekoppling mellan begrepp" }, { text: "Symbolik" }], correct: 1, difficulty: "elit" },
  { word: "Tautologi", options: [{ text: "Ny iakttagelse" }, { text: "Tomupprepning", hint: "Onödig upprepning av samma innebörd" }, { text: "Motsägelse", hint: "Påstående som strider mot sig självt" }, { text: "Sammanfattning" }], correct: 1, difficulty: "elit" },
  { word: "Metafysisk", options: [{ text: "Mätbar" }, { text: "Översinnlig", hint: "Bortom det fysiskt iakttagbara" }, { text: "Materiell" }, { text: "Teknisk" }], correct: 1, difficulty: "elit" },
  { word: "Idiosynkrasi", options: [{ text: "Utbredd vana", hint: "Beteende som delas av många" }, { text: "Egenhet", hint: "Mycket personlig säregenhet" }, { text: "Regel" }, { text: "Naturlag" }], correct: 1, difficulty: "elit" },
  { word: "Hybris", options: [{ text: "Självinsikt" }, { text: "Övermod" }, { text: "Ödmjukhet" }, { text: "Svaghet" }], correct: 1, difficulty: "elit" },
  { word: "Katalysator", options: [{ text: "Hinder" }, { text: "Pådrivare", hint: "Utlösande kraft som påskyndar något" }, { text: "Biprodukt" }, { text: "Bromsare" }], correct: 1, difficulty: "elit" },
  { word: "Paradigmskifte", options: [{ text: "Detaljjustering", hint: "Mindre finputs utan grundläggande omläggning" }, { text: "Tankramsbyte", hint: "Grundläggande byte av förståelsemodell" }, { text: "Trend" }, { text: "Nyans" }], correct: 1, difficulty: "elit" },
  { word: "Oxymoron", options: [{ text: "Resonemang" }, { text: "Motsägelsebild", hint: "Två ord som motsäger varandra" }, { text: "Upprepning" }, { text: "Rim" }], correct: 1, difficulty: "elit" },
  { word: "Katarsis", options: [{ text: "Förströelse", hint: "Lättsam underhållning som skingrar tankarna" }, { text: "Rening", hint: "Befrielse via djup känslomässig upplevelse" }, { text: "Analys" }, { text: "Ceremoni" }], correct: 1, difficulty: "elit" },
  { word: "Synkretism", options: [{ text: "Avgränsning", hint: "Strikt åtskillnad mellan idéer eller traditioner" }, { text: "Sammansmältning", hint: "Element från skilda traditioner förenas" }, { text: "Rensning" }, { text: "Strid" }], correct: 1, difficulty: "elit" },
  { word: "Dikotomi", options: [{ text: "Glidande skala", hint: "Steglös övergång utan tydliga gränser" }, { text: "Tudelning", hint: "Skarp uppdelning i två oförenliga delar" }, { text: "Mångfald" }, { text: "Helhet" }], correct: 1, difficulty: "elit" },
  { word: "Palimpsest", options: [{ text: "Nyskrivet" }, { text: "Överskriven yta", hint: "Yta där gammal text skrapats bort och ny skrivits över" }, { text: "Kopia" }, { text: "Tom yta" }], correct: 1, difficulty: "elit" },
  { word: "Demagog", options: [{ text: "Debattör" }, { text: "Folkuppviglare", hint: "Agitator som spelar på massans känslor" }, { text: "Filosof" }, { text: "Medlare", hint: "Person som dämpar konflikter och förenar parter" }], correct: 1, difficulty: "elit" },
  { word: "Epifani", options: [{ text: "Inlärning" }, { text: "Uppenbarelse", hint: "Plötslig och klar insikt" }, { text: "Iakttagelse", hint: "Sakligt observerande utan plötslig insikt" }, { text: "Slutsats" }], correct: 1, difficulty: "elit" },
  { word: "Obsolet", options: [{ text: "Aktuell" }, { text: "Föråldrad" }, { text: "Nyuppfunnen" }, { text: "Ur drift" }], correct: 1, difficulty: "elit" },
  { word: "Nepotism", options: [{ text: "Meritbaserat", hint: "Tillsättning som styrs av prestation och förmåga" }, { text: "Svågerpolitik", hint: "Gynnande av släkt på andras bekostnad" }, { text: "Konkurrens" }, { text: "Byråkrati" }], correct: 1, difficulty: "elit" },
  { word: "Polyvalent", options: [{ text: "Enspårig" }, { text: "Mångsidig", hint: "Användbar i flera olika sammanhang" }, { text: "Obrukbar" }, { text: "Specialiserad", hint: "Inriktad på ett enda smalt område" }], correct: 1, difficulty: "elit" },
  { word: "Solipsism", options: [{ text: "Objektiv värld" }, { text: "Jagfilosofi", hint: "Tron att bara det egna jaget säkert existerar" }, { text: "Kollektivism", hint: "Filosofi som ger gemenskapen företräde framför individen" }, { text: "Materialism" }], correct: 1, difficulty: "elit" },
  { word: "Autarki", options: [{ text: "Beroende" }, { text: "Självförsörjning", hint: "Klarar sig utan utbyte med omvärlden" }, { text: "Fri handel", hint: "System där varor utbyts fritt över gränser" }, { text: "Militärberoende" }], correct: 1, difficulty: "elit" },
  { word: "Mimesis", options: [{ text: "Originalitet", hint: "Friskt eget skapande utan föregångare" }, { text: "Efterbildning", hint: "Efterliknande eller avbildning av verkligheten" }, { text: "Spekulation" }, { text: "Förstörelse" }], correct: 1, difficulty: "elit" },
  { word: "Proleptisk", options: [{ text: "Bakåtblickande", hint: "Inriktad mot det som redan har varit" }, { text: "Föregripande", hint: "Som förutser eller tar något i förväg" }, { text: "Stillastående" }, { text: "Tidlös" }], correct: 1, difficulty: "elit" },
  { word: "Elyseisk", options: [{ text: "Skräckinjagande" }, { text: "Lycksalig", hint: "Himmelskt salig och skön" }, { text: "Vardaglig" }, { text: "Armodspräglad", hint: "Tyngd av fattigdom och nöd" }], correct: 1, difficulty: "elit" },
  { word: "Ikonoklast", options: [{ text: "Traditionalist", hint: "Den som bevarar gamla seder och idéer" }, { text: "Bildstormare", hint: "Någon som bryter ner vedertagna idoler" }, { text: "Efterhärmare" }, { text: "Passiv" }], correct: 1, difficulty: "elit" },
  { word: "Zeitgeist", options: [{ text: "Personlighet" }, { text: "Tidsanda", hint: "Den rådande epokens präglande stämning" }, { text: "Geografi" }, { text: "Indikator" }], correct: 1, difficulty: "elit" },
  { word: "Agnostisk", options: [{ text: "Trossäker", hint: "Helt övertygad i sin tro utan tvivel" }, { text: "Tvehågsen", hint: "Anser frågan omöjlig att avgöra med visshet" }, { text: "Förnekande" }, { text: "Strikt religiös" }], correct: 1, difficulty: "elit" },
  { word: "Reifiera", options: [{ text: "Upplösa" }, { text: "Konkretisera", hint: "Göra ett abstrakt begrepp till ett ting" }, { text: "Förneka" }, { text: "Beskriva" }], correct: 1, difficulty: "elit" },
  { word: "Nihilism", options: [{ text: "Värdetro", hint: "Övertygelse om att verkliga värden finns" }, { text: "Värdeförnekelse", hint: "Uppfattningen att inga verkliga värden finns" }, { text: "Optimism" }, { text: "Religion" }], correct: 1, difficulty: "elit" }

];
